version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kopi_ngumpul_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=89.116.34.103
      - DB_PORT=5432
      - DB_DATABASE=kopi_ngumpul
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on: []
